CREATE TABLE `cortex_connections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`platform` varchar(64) NOT NULL,
	`displayName` varchar(256) NOT NULL DEFAULT '',
	`baseUrl` varchar(512) NOT NULL DEFAULT '',
	`outboundApiKey` varchar(512) NOT NULL DEFAULT '',
	`inboundApiKey` varchar(512) NOT NULL DEFAULT '',
	`webhookUrl` varchar(512) NOT NULL DEFAULT '',
	`syncIntervalSeconds` int NOT NULL DEFAULT 300,
	`enabled` boolean NOT NULL DEFAULT false,
	`lastHealthCheck` timestamp,
	`lastHealthStatus` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cortex_connections_id` PRIMARY KEY(`id`),
	CONSTRAINT `cortex_connections_platform_unique` UNIQUE(`platform`)
);
--> statement-breakpoint
CREATE TABLE `cortex_returns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`returnNumber` varchar(128) NOT NULL,
	`orderId` varchar(256),
	`orderNumber` varchar(128),
	`extensivCustomerId` int,
	`customerId` varchar(256),
	`customerName` varchar(256) NOT NULL DEFAULT '',
	`reason` varchar(256),
	`items` json,
	`shippingAddress` json,
	`notes` text,
	`status` varchar(64) NOT NULL DEFAULT 'Received',
	`inspectionResult` text,
	`disposition` varchar(64),
	`refundAmount` decimal(10,2),
	`refundApproved` boolean,
	`processedBy` varchar(256),
	`processedAt` timestamp,
	`returnsSessionId` int,
	`webhookSent` boolean NOT NULL DEFAULT false,
	`clearsightCreatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cortex_returns_id` PRIMARY KEY(`id`)
);
