CREATE TABLE `production_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` varchar(64) NOT NULL,
	`lineId` varchar(64) NOT NULL DEFAULT 'LINE-1',
	`operatorId` varchar(256) NOT NULL,
	`expectedGtin` varchar(20) NOT NULL,
	`expectedLot` varchar(128) NOT NULL,
	`expectedExpiry` varchar(10) NOT NULL,
	`confidenceThreshold` decimal(4,3) NOT NULL DEFAULT '0.850',
	`shelfLifeDaysMin` int,
	`holdConfidenceMin` decimal(4,3),
	`tampDefaultX` decimal(8,2),
	`tampDefaultY` decimal(8,2),
	`status` enum('active','closed','aborted') NOT NULL DEFAULT 'active',
	`totalScanned` int NOT NULL DEFAULT 0,
	`totalPass` int NOT NULL DEFAULT 0,
	`totalFail` int NOT NULL DEFAULT 0,
	`totalHold` int NOT NULL DEFAULT 0,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`closedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `production_runs_id` PRIMARY KEY(`id`),
	CONSTRAINT `production_runs_runId_unique` UNIQUE(`runId`)
);
--> statement-breakpoint
CREATE TABLE `production_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` varchar(64) NOT NULL,
	`runId` varchar(64) NOT NULL,
	`cartonId` varchar(64) NOT NULL,
	`scannedGtin` varchar(20),
	`scannedLot` varchar(128),
	`scannedExpiry` varchar(10),
	`scannedSerial` varchar(128),
	`poNumber` varchar(128),
	`skuBbox` json,
	`camBClear` boolean,
	`confidence` decimal(5,4),
	`verdict` enum('pass','fail','hold') NOT NULL,
	`failReason` varchar(64),
	`placement` enum('over_sku','fixed_default'),
	`tampXMm` decimal(8,2),
	`tampYMm` decimal(8,2),
	`zplSent` text,
	`printedAt` timestamp,
	`scannedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `production_scans_id` PRIMARY KEY(`id`),
	CONSTRAINT `production_scans_scanId_unique` UNIQUE(`scanId`)
);
--> statement-breakpoint
CREATE TABLE `production_sku_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gtin` varchar(20) NOT NULL,
	`skuDescription` varchar(256),
	`shelfLifeDaysMin` int NOT NULL DEFAULT 30,
	`holdConfidenceMin` decimal(4,3) DEFAULT '0.700',
	`lotPattern` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `production_sku_configs_id` PRIMARY KEY(`id`),
	CONSTRAINT `production_sku_configs_gtin_unique` UNIQUE(`gtin`)
);
