-- Migration: unified shipments table
-- Captures tracking numbers from all GD shipping platforms:
--   veeqo (small parcel), techship (small parcel), shipwell (LTL), manual

CREATE TABLE IF NOT EXISTS `shipments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `platform` enum('veeqo','techship','shipwell','manual') NOT NULL,
  `mode` enum('small_parcel','ltl','ftl','other') NOT NULL DEFAULT 'small_parcel',
  `config_id` int,
  `extensiv_order_id` int,
  `order_number` varchar(128),
  `customer_id` int,
  `customer_name` varchar(255),
  `facility_name` varchar(128),
  `ship_to_name` varchar(255),
  `ship_to_address1` varchar(255),
  `ship_to_city` varchar(128),
  `ship_to_state` varchar(64),
  `ship_to_zip` varchar(20),
  `ship_to_country` varchar(4) DEFAULT 'US',
  `carrier` varchar(128),
  `service_level` varchar(256),
  `carrier_scac` varchar(10),
  `tracking_number` varchar(256),
  `bol_number` varchar(128),
  `pro_number` varchar(128),
  `shipwell_order_id` varchar(128),
  `shipwell_shipment_id` varchar(128),
  `veeqo_shipment_id` varchar(128),
  `rate_wizard_shipment_id` int,
  `small_parcel_session_id` int,
  `weight_lbs` decimal(8,2),
  `label_cost_cents` int,
  `raw_cost_cents` int,
  `currency` varchar(4) DEFAULT 'USD',
  `label_url` text,
  `label_zpl` text,
  `status` varchar(32) DEFAULT 'booked',
  `shipwell_status` varchar(64),
  `estimated_delivery_at` timestamp NULL,
  `delivered_at` timestamp NULL,
  `booked_by_user_id` varchar(128),
  `booked_by_name` varchar(255),
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shipments_tracking` (`tracking_number`),
  INDEX `idx_shipments_order` (`extensiv_order_id`),
  INDEX `idx_shipments_order_number` (`order_number`),
  INDEX `idx_shipments_platform` (`platform`),
  INDEX `idx_shipments_created_at` (`created_at`),
  INDEX `idx_shipments_customer` (`customer_id`),
  INDEX `idx_shipments_facility` (`facility_name`(64))
);
