CREATE TABLE `routing_guides` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `config_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `customer_name` varchar(255) NOT NULL,
  `dest_country` varchar(2),
  `dest_state` varchar(64),
  `dest_zip_from` varchar(16),
  `dest_zip_to` varchar(16),
  `dest_city` varchar(128),
  `required_carrier` varchar(64),
  `required_service` varchar(128),
  `required_account` varchar(128),
  `max_transit_days` int,
  `requires_residential` boolean NOT NULL DEFAULT false,
  `requires_signature` boolean NOT NULL DEFAULT false,
  `requires_adult_signature` boolean NOT NULL DEFAULT false,
  `requires_saturday_delivery` boolean NOT NULL DEFAULT false,
  `label_instructions` text,
  `notes` text,
  `priority` int NOT NULL DEFAULT 0,
  `is_active` boolean NOT NULL DEFAULT true,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL
);
